### ISSUE TITLE
clean function

### ISSUE THREAD

**Issue by Torrecilla** [PyxelCoder/LightBox#3]
On /\* CLEAN */
add at the end:
location.reload();

Some browsers do not fully reset everything, and click event may be forgotten from other functions. Tested with this line and works good.

Good job, can' wait to check the lightbox V2 :D

**Comment by PyxelCoder** [comment]
Thanks ;)

**Comment by MonsieurLanza** [comment]
This is due to #4.
Please do NOT reload page to fix the issue.
